version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/asistente_salud
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - asistente-network

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=asistente_salud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - asistente-network

volumes:
  postgres_data:

networks:
  asistente-network:
    driver: bridge 